/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedQuestionsRouteImport } from './routes/_authenticated/questions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedLessonsIndexRouteImport } from './routes/_authenticated/lessons.index'
import { Route as AuthenticatedBootcampsIndexRouteImport } from './routes/_authenticated/bootcamps.index'
import { Route as AuthenticatedAnnouncementsIndexRouteImport } from './routes/_authenticated/announcements.index'
import { Route as ApiPublicAskQuestionRouteImport } from './routes/api/public/ask-question'
import { Route as AuthenticatedLessonsTestBrainRouteImport } from './routes/_authenticated/lessons.test-brain'
import { Route as AuthenticatedLessonsIdRouteImport } from './routes/_authenticated/lessons.$id'
import { Route as AuthenticatedBootcampsIdRouteImport } from './routes/_authenticated/bootcamps.$id'
import { Route as AuthenticatedAnnouncementsNewRouteImport } from './routes/_authenticated/announcements.new'
import { Route as AuthenticatedAnnouncementsIdRouteImport } from './routes/_authenticated/announcements.$id'
import { Route as AuthenticatedAdminPasswordRequestsRouteImport } from './routes/_authenticated/admin.password-requests'
import { Route as ApiPublicHooksReconcileIndexingRouteImport } from './routes/api/public/hooks/reconcile-indexing'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionsRoute = AuthenticatedQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLessonsIndexRoute =
  AuthenticatedLessonsIndexRouteImport.update({
    id: '/lessons/',
    path: '/lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBootcampsIndexRoute =
  AuthenticatedBootcampsIndexRouteImport.update({
    id: '/bootcamps/',
    path: '/bootcamps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnouncementsIndexRoute =
  AuthenticatedAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAskQuestionRoute = ApiPublicAskQuestionRouteImport.update({
  id: '/api/public/ask-question',
  path: '/api/public/ask-question',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLessonsTestBrainRoute =
  AuthenticatedLessonsTestBrainRouteImport.update({
    id: '/lessons/test-brain',
    path: '/lessons/test-brain',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsIdRoute = AuthenticatedLessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBootcampsIdRoute =
  AuthenticatedBootcampsIdRouteImport.update({
    id: '/bootcamps/$id',
    path: '/bootcamps/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnouncementsNewRoute =
  AuthenticatedAnnouncementsNewRouteImport.update({
    id: '/announcements/new',
    path: '/announcements/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnouncementsIdRoute =
  AuthenticatedAnnouncementsIdRouteImport.update({
    id: '/announcements/$id',
    path: '/announcements/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPasswordRequestsRoute =
  AuthenticatedAdminPasswordRequestsRouteImport.update({
    id: '/admin/password-requests',
    path: '/admin/password-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksReconcileIndexingRoute =
  ApiPublicHooksReconcileIndexingRouteImport.update({
    id: '/api/public/hooks/reconcile-indexing',
    path: '/api/public/hooks/reconcile-indexing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/password-requests': typeof AuthenticatedAdminPasswordRequestsRoute
  '/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/announcements/new': typeof AuthenticatedAnnouncementsNewRoute
  '/bootcamps/$id': typeof AuthenticatedBootcampsIdRoute
  '/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/lessons/test-brain': typeof AuthenticatedLessonsTestBrainRoute
  '/api/public/ask-question': typeof ApiPublicAskQuestionRoute
  '/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
  '/bootcamps/': typeof AuthenticatedBootcampsIndexRoute
  '/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/api/public/hooks/reconcile-indexing': typeof ApiPublicHooksReconcileIndexingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/password-requests': typeof AuthenticatedAdminPasswordRequestsRoute
  '/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/announcements/new': typeof AuthenticatedAnnouncementsNewRoute
  '/bootcamps/$id': typeof AuthenticatedBootcampsIdRoute
  '/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/lessons/test-brain': typeof AuthenticatedLessonsTestBrainRoute
  '/api/public/ask-question': typeof ApiPublicAskQuestionRoute
  '/announcements': typeof AuthenticatedAnnouncementsIndexRoute
  '/bootcamps': typeof AuthenticatedBootcampsIndexRoute
  '/lessons': typeof AuthenticatedLessonsIndexRoute
  '/api/public/hooks/reconcile-indexing': typeof ApiPublicHooksReconcileIndexingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/questions': typeof AuthenticatedQuestionsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/admin/password-requests': typeof AuthenticatedAdminPasswordRequestsRoute
  '/_authenticated/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/_authenticated/announcements/new': typeof AuthenticatedAnnouncementsNewRoute
  '/_authenticated/bootcamps/$id': typeof AuthenticatedBootcampsIdRoute
  '/_authenticated/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/_authenticated/lessons/test-brain': typeof AuthenticatedLessonsTestBrainRoute
  '/api/public/ask-question': typeof ApiPublicAskQuestionRoute
  '/_authenticated/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
  '/_authenticated/bootcamps/': typeof AuthenticatedBootcampsIndexRoute
  '/_authenticated/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/api/public/hooks/reconcile-indexing': typeof ApiPublicHooksReconcileIndexingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/dashboard'
    | '/questions'
    | '/students'
    | '/invite/$token'
    | '/admin/password-requests'
    | '/announcements/$id'
    | '/announcements/new'
    | '/bootcamps/$id'
    | '/lessons/$id'
    | '/lessons/test-brain'
    | '/api/public/ask-question'
    | '/announcements/'
    | '/bootcamps/'
    | '/lessons/'
    | '/api/public/hooks/reconcile-indexing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/dashboard'
    | '/questions'
    | '/students'
    | '/invite/$token'
    | '/admin/password-requests'
    | '/announcements/$id'
    | '/announcements/new'
    | '/bootcamps/$id'
    | '/lessons/$id'
    | '/lessons/test-brain'
    | '/api/public/ask-question'
    | '/announcements'
    | '/bootcamps'
    | '/lessons'
    | '/api/public/hooks/reconcile-indexing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/questions'
    | '/_authenticated/students'
    | '/invite/$token'
    | '/_authenticated/admin/password-requests'
    | '/_authenticated/announcements/$id'
    | '/_authenticated/announcements/new'
    | '/_authenticated/bootcamps/$id'
    | '/_authenticated/lessons/$id'
    | '/_authenticated/lessons/test-brain'
    | '/api/public/ask-question'
    | '/_authenticated/announcements/'
    | '/_authenticated/bootcamps/'
    | '/_authenticated/lessons/'
    | '/api/public/hooks/reconcile-indexing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicAskQuestionRoute: typeof ApiPublicAskQuestionRoute
  ApiPublicHooksReconcileIndexingRoute: typeof ApiPublicHooksReconcileIndexingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions': {
      id: '/_authenticated/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedQuestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/': {
      id: '/_authenticated/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AuthenticatedLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bootcamps/': {
      id: '/_authenticated/bootcamps/'
      path: '/bootcamps'
      fullPath: '/bootcamps/'
      preLoaderRoute: typeof AuthenticatedBootcampsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/': {
      id: '/_authenticated/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ask-question': {
      id: '/api/public/ask-question'
      path: '/api/public/ask-question'
      fullPath: '/api/public/ask-question'
      preLoaderRoute: typeof ApiPublicAskQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lessons/test-brain': {
      id: '/_authenticated/lessons/test-brain'
      path: '/lessons/test-brain'
      fullPath: '/lessons/test-brain'
      preLoaderRoute: typeof AuthenticatedLessonsTestBrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/$id': {
      id: '/_authenticated/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof AuthenticatedLessonsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bootcamps/$id': {
      id: '/_authenticated/bootcamps/$id'
      path: '/bootcamps/$id'
      fullPath: '/bootcamps/$id'
      preLoaderRoute: typeof AuthenticatedBootcampsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/new': {
      id: '/_authenticated/announcements/new'
      path: '/announcements/new'
      fullPath: '/announcements/new'
      preLoaderRoute: typeof AuthenticatedAnnouncementsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/$id': {
      id: '/_authenticated/announcements/$id'
      path: '/announcements/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/password-requests': {
      id: '/_authenticated/admin/password-requests'
      path: '/admin/password-requests'
      fullPath: '/admin/password-requests'
      preLoaderRoute: typeof AuthenticatedAdminPasswordRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/reconcile-indexing': {
      id: '/api/public/hooks/reconcile-indexing'
      path: '/api/public/hooks/reconcile-indexing'
      fullPath: '/api/public/hooks/reconcile-indexing'
      preLoaderRoute: typeof ApiPublicHooksReconcileIndexingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedQuestionsRoute: typeof AuthenticatedQuestionsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedAdminPasswordRequestsRoute: typeof AuthenticatedAdminPasswordRequestsRoute
  AuthenticatedAnnouncementsIdRoute: typeof AuthenticatedAnnouncementsIdRoute
  AuthenticatedAnnouncementsNewRoute: typeof AuthenticatedAnnouncementsNewRoute
  AuthenticatedBootcampsIdRoute: typeof AuthenticatedBootcampsIdRoute
  AuthenticatedLessonsIdRoute: typeof AuthenticatedLessonsIdRoute
  AuthenticatedLessonsTestBrainRoute: typeof AuthenticatedLessonsTestBrainRoute
  AuthenticatedAnnouncementsIndexRoute: typeof AuthenticatedAnnouncementsIndexRoute
  AuthenticatedBootcampsIndexRoute: typeof AuthenticatedBootcampsIndexRoute
  AuthenticatedLessonsIndexRoute: typeof AuthenticatedLessonsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedQuestionsRoute: AuthenticatedQuestionsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedAdminPasswordRequestsRoute:
    AuthenticatedAdminPasswordRequestsRoute,
  AuthenticatedAnnouncementsIdRoute: AuthenticatedAnnouncementsIdRoute,
  AuthenticatedAnnouncementsNewRoute: AuthenticatedAnnouncementsNewRoute,
  AuthenticatedBootcampsIdRoute: AuthenticatedBootcampsIdRoute,
  AuthenticatedLessonsIdRoute: AuthenticatedLessonsIdRoute,
  AuthenticatedLessonsTestBrainRoute: AuthenticatedLessonsTestBrainRoute,
  AuthenticatedAnnouncementsIndexRoute: AuthenticatedAnnouncementsIndexRoute,
  AuthenticatedBootcampsIndexRoute: AuthenticatedBootcampsIndexRoute,
  AuthenticatedLessonsIndexRoute: AuthenticatedLessonsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicAskQuestionRoute: ApiPublicAskQuestionRoute,
  ApiPublicHooksReconcileIndexingRoute: ApiPublicHooksReconcileIndexingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
