/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBootcampsRouteImport } from './routes/_authenticated/bootcamps'
import { Route as ApiPublicAskQuestionRouteImport } from './routes/api/public/ask-question'
import { Route as AuthenticatedBootcampsIdRouteImport } from './routes/_authenticated/bootcamps.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBootcampsRoute = AuthenticatedBootcampsRouteImport.update({
  id: '/bootcamps',
  path: '/bootcamps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAskQuestionRoute = ApiPublicAskQuestionRouteImport.update({
  id: '/api/public/ask-question',
  path: '/api/public/ask-question',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBootcampsIdRoute =
  AuthenticatedBootcampsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedBootcampsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bootcamps': typeof AuthenticatedBootcampsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/bootcamps/$id': typeof AuthenticatedBootcampsIdRoute
  '/api/public/ask-question': typeof ApiPublicAskQuestionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bootcamps': typeof AuthenticatedBootcampsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/bootcamps/$id': typeof AuthenticatedBootcampsIdRoute
  '/api/public/ask-question': typeof ApiPublicAskQuestionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/bootcamps': typeof AuthenticatedBootcampsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/bootcamps/$id': typeof AuthenticatedBootcampsIdRoute
  '/api/public/ask-question': typeof ApiPublicAskQuestionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/bootcamps'
    | '/dashboard'
    | '/students'
    | '/bootcamps/$id'
    | '/api/public/ask-question'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/bootcamps'
    | '/dashboard'
    | '/students'
    | '/bootcamps/$id'
    | '/api/public/ask-question'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/bootcamps'
    | '/_authenticated/dashboard'
    | '/_authenticated/students'
    | '/_authenticated/bootcamps/$id'
    | '/api/public/ask-question'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicAskQuestionRoute: typeof ApiPublicAskQuestionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bootcamps': {
      id: '/_authenticated/bootcamps'
      path: '/bootcamps'
      fullPath: '/bootcamps'
      preLoaderRoute: typeof AuthenticatedBootcampsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ask-question': {
      id: '/api/public/ask-question'
      path: '/api/public/ask-question'
      fullPath: '/api/public/ask-question'
      preLoaderRoute: typeof ApiPublicAskQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bootcamps/$id': {
      id: '/_authenticated/bootcamps/$id'
      path: '/$id'
      fullPath: '/bootcamps/$id'
      preLoaderRoute: typeof AuthenticatedBootcampsIdRouteImport
      parentRoute: typeof AuthenticatedBootcampsRoute
    }
  }
}

interface AuthenticatedBootcampsRouteChildren {
  AuthenticatedBootcampsIdRoute: typeof AuthenticatedBootcampsIdRoute
}

const AuthenticatedBootcampsRouteChildren: AuthenticatedBootcampsRouteChildren =
  {
    AuthenticatedBootcampsIdRoute: AuthenticatedBootcampsIdRoute,
  }

const AuthenticatedBootcampsRouteWithChildren =
  AuthenticatedBootcampsRoute._addFileChildren(
    AuthenticatedBootcampsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBootcampsRoute: typeof AuthenticatedBootcampsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBootcampsRoute: AuthenticatedBootcampsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicAskQuestionRoute: ApiPublicAskQuestionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
